controller_list:
  - name: fake_right_leg_controller
    joints:
      - r_hip_yaw
      - r_hip_roll
      - r_hip_pitch
      - r_knee_pitch
      - r_ankle_pitch
      - r_ankle_roll
  - name: fake_left_leg_controller
    joints:
      - l_hip_yaw
      - l_hip_roll
      - l_hip_pitch
      - l_knee_pitch
      - l_ankle_pitch
      - l_ankle_roll
  - name: fake_right_arm_controller
    joints:
      - r_shoulder_pitch
      - r_shoulder_roll
      - r_shoulder_yaw
      - r_elbow_pitch
      - r_wrist_yaw
      - r_wrist_pitch
  - name: fake_left_arm_controller
    joints:
      - l_shoulder_pitch
      - l_shoulder_roll
      - l_shoulder_yaw
      - l_elbow_pitch
      - l_wrist_yaw
      - l_wrist_pitch
  - name: fake_right_gripper_controller
    joints:
      - r_wrist_yaw
      - r_wrist_pitch
  - name: fake_left_gripper_controller
    joints:
      - l_wrist_yaw
      - l_wrist_pitch